name: 📚 Generate Documentation

on:
  push:
    tags:
      - 'v*'

jobs:
  run:
    name: 📚 Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🏗️ Setup Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: 📚 Generate Documentation
        run: |
          doxygen Doxyfile

      - name: 📁 Archive Documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: html